# Playbook to deploy k8s

---

- name: Common setup
  hosts: all
  become: true
  tags: common_setup

  roles:
    - common_config
    - common_software

- name: Deploy control plane
  hosts: '{{ groups["controllers"] | first }}'
  become: true
  tags: control_plane

  roles:
    - control_plane

- name: Configure workers
  hosts: workers
  become: true
  tags: workers

  roles:
    - worker

- name: Deploy Helm charts
  hosts: '{{ groups["controllers"] | first }}'
  become: true
  tags: charts

  roles:
    - charts
