---

- name: Ensure helm repository key exists
  apt_key:
    url: 'https://baltocdn.com/helm/signing.asc'


- name: Ensure helm repository exists
  apt_repository:
    repo: 'deb https://baltocdn.com/helm/stable/debian/ all main'

- name: Ensure helm is installed
  apt:
    name: 'helm'

- name: Ensure helm diff plugin is installed
  kubernetes.core.helm_plugin:
    plugin_path: 'https://github.com/databus23/helm-diff'
    state: 'present'
