---

- name: Ensure vagrant uuser .kube directory exists
  file:
    path: '/home/vagrant/.kube'
    state: 'directory'
    mode: '0755'
    owner: 'vagrant'
    group: 'vagrant'

- name: Ensure kube config exists for VMs and host
  copy:
    remote_src: true
    src: '/etc/kubernetes/admin.conf'
    dest: '{{ item }}'
    mode: '0600'
    owner: 'vagrant'
    group: 'vagrant'
  loop:
    - '/vagrant/kube_config'
    - '/home/vagrant/.kube/config'
