---

- import_tasks: init.yml
  tags: init

- import_tasks: kubeconfig.yml
  tags: kubeconfig

- import_tasks: token.yml
  tags: workers

- import_tasks: '{{ k8s_network_plugin }}.yml'

- import_tasks: helm.yml
  tags: helm
