---

- import_tasks: init.yml
- import_tasks: kubeconfig.yml
- import_tasks: token.yml
  tags: workers
- import_tasks: '{{ k8s_network_plugin }}.yml'
- import_tasks: helm.yml
- import_tasks: metallb.yml
- import_tasks: ingress.yml
