# Use with:
# helm repo add jenkins https://charts.jenkins.io
# helm repo update
# helm install jenkins jenkins/jenkins -f apps/jenkins-values.yml
controller:
  ingress:
    enabled: true
    apiVersion: "extensions/v1beta1"
    annotations:
      kubernetes.io/ingress.class: "nginx"
