---

metallb_address_range: '192.168.33.200-192.168.33.250'
metrics_server_replicas: 2
nfs_server: '192.168.33.3'
nfs_path: '/k8s_data'

charts:
  - chart_repo_name: 'metallb'
    chart_repo_url: 'https://metallb.github.io/metallb'
    release_name: 'metallb'
    chart_ref: 'metallb'
    release_namespace: 'metallb-system'
    release_values:
      configInline:
        address-pools:
          - name: 'default'
            protocol: 'layer2'
            addresses:
            - '{{ metallb_address_range }}'

  - chart_repo_name: 'ingress-nginx'
    chart_repo_url: 'https://kubernetes.github.io/ingress-nginx'
    release_name: 'ingress-nginx'
    chart_ref: 'ingress-nginx'
    release_namespace: 'ingress-nginx'

  - chart_repo_name: 'metrics-server'
    chart_repo_url: 'https://kubernetes-sigs.github.io/metrics-server/'
    release_name: 'metrics-server'
    chart_ref: 'metrics-server'
    release_namespace: 'metrics'
    release_values:
      args: ['--kubelet-insecure-tls']
      replicas: '{{ metrics_server_replicas | int }}'

  - chart_repo_name: 'nfs-subdir-external-provisioner'
    chart_repo_url: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'
    release_name: 'nfs-subdir-external-provisioner'
    chart_ref: 'nfs-subdir-external-provisioner'
    release_namespace: 'nfs-subdir-external-provisioner'
    release_values:
      nfs:
        server: '{{ nfs_server }}'
        path: '{{ nfs_path }}'
      storageClass:
        defaultClass: true

  - chart_repo_name: 'prometheus-community'
    chart_repo_url: 'https://prometheus-community.github.io/helm-charts'
    release_name: 'kube-prometheus-stack'
    chart_ref: 'kube-prometheus-stack'
    chart_version: '34.10.0'
    release_namespace: 'default'
    release_values:
      grafana:
        defaultDashboardsTimezone: 'America/Los_Angeles'
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: 'nginx'
          path: '/grafana'
